# Generated by Django 4.0.1 on 2022-03-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RessourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='ressources',
            field=models.ManyToManyField(through='main.RessourceCategory', to='main.Ressource'),
        ),
        migrations.AlterField(
            model_name='category',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.base'),
        ),
        migrations.AddField(
            model_name='ressourcecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AddField(
            model_name='ressourcecategory',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ressource'),
        ),
    ]
