# Generated by Django 4.0.2 on 2022-06-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bases', to='main.Tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='users', to='main.Tag'),
        ),
    ]
