# Generated by Django 4.0.2 on 2022-06-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_base_tags_user_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='linked_resources',
        ),
        migrations.AddField(
            model_name='base',
            name='pinned_collections',
            field=models.ManyToManyField(blank=True, related_name='pinned_in_bases', to='main.Collection',
                                         verbose_name='Collections enregistrées'),
        ),
        migrations.AddField(
            model_name='base',
            name='pinned_resources',
            field=models.ManyToManyField(blank=True, related_name='pinned_in_bases', to='main.Resource',
                                         verbose_name='Ressources enregistrées'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
