# Generated by Django 4.0.5 on 2022-06-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_resource_linked_resources_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='cnfs_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
