# Generated by Django 4.0.5 on 2022-06-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_resource_linked_resources_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
        migrations.AddField(
            model_name='base',
            name='contributor_tags',
            field=models.ManyToManyField(blank=True, related_name='contributor_in_bases', to='main.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
