# Generated by Django 4.0.2 on 2022-04-25 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contentblock_contentfolder_contributorprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='internal_producer',
            new_name='internal_producers',
        ),
        migrations.RenameField(
            model_name='tagcategory',
            old_name='required_to_public',
            new_name='required_to_be_public',
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='main.tagcategory'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='main.tag'),
        ),
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=20)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.resource')),
            ],
            options={
                'verbose_name': 'Dossier de contenu',
                'verbose_name_plural': 'Dossiers de contenu',
            },
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contentsection'),
        ),
        migrations.DeleteModel(
            name='ContentFolder',
        ),
    ]
