# Generated by Django 4.0.2 on 2022-04-05 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_contributorprofile_externalproducer_resource_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=20)),
                ('annotation', models.TextField()),
                ('is_draft', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Bloc de contenu',
                'verbose_name_plural': 'Blocs de contenu',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='definition',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='accepts_free_tags',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='is_multi_select',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='required_to_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='internal_producer',
            field=models.ManyToManyField(blank=True, related_name='internal_producers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='linked_resources',
            field=models.ManyToManyField(blank=True, to='main.Resource'),
        ),
        migrations.CreateModel(
            name='ContentFolder',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.contentblock')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contentfolder')),
            ],
            options={
                'verbose_name': 'Dossier de contenu',
                'verbose_name_plural': 'Dossiers de contenu',
            },
            bases=('main.contentblock',),
        ),
        migrations.CreateModel(
            name='TextResource',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.contentblock')),
                ('text', models.TextField()),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contentfolder')),
            ],
            options={
                'verbose_name': 'Contenu : Texte',
                'verbose_name_plural': 'Contenus : Textes',
            },
            bases=('main.contentblock',),
        ),
        migrations.CreateModel(
            name='LinkedResourceContent',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.contentblock')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contentfolder')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.resource')),
            ],
            options={
                'verbose_name': 'Contenu : Ressource liée',
                'verbose_name_plural': 'Contenus : Ressources liées',
            },
            bases=('main.contentblock',),
        ),
        migrations.CreateModel(
            name='LinkContent',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.contentblock')),
                ('link', models.URLField()),
                ('display_mode', models.CharField(choices=[('embedded', 'Page intégrée'), ('simple', 'Lien simple'), ('bookmark', 'Marque-page')], max_length=10)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contentfolder')),
            ],
            options={
                'verbose_name': 'Contenu : Lien externe',
                'verbose_name_plural': 'Contenus : Liens externes',
            },
            bases=('main.contentblock',),
        ),
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.contentblock')),
                ('file', models.FileField(upload_to='')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contentfolder')),
            ],
            options={
                'verbose_name': 'Contenu : Fichier importé',
                'verbose_name_plural': 'Contenus : Fichiers importés',
            },
            bases=('main.contentblock',),
        ),
    ]
