# Generated by Django 4.0.5 on 2022-06-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_collection_options_base_contributor_tags_and_more'),
        ('main', '0004_alter_collection_options_user_cnfs_id_and_more'),
    ]

    operations = [
    ]
