# Generated by Django 4.0.2 on 2022-04-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_internal_producer_resource_internal_producers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='content',
        ),
    ]
