# Generated by Django 4.0.2 on 2022-06-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_merge_20220617_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='base',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Privé')], max_length=10,
                                   null=True, verbose_name='Accès au mail'),
        ),
        migrations.AddField(
            model_name='base',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='base',
            name='description',
            field=models.CharField(blank=True, max_length=560, null=True),
        ),
        migrations.AddField(
            model_name='base',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='base',
            name='state',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Privé'), ('restricted', 'Restreint'),
                                            ('draft', 'Brouillon')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='base',
            name='contributor_tags',
            field=models.ManyToManyField(blank=True, related_name='contributor_in_bases', to='main.Tag'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='state',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Privé'), ('restricted', 'Restreint'),
                                            ('draft', 'Brouillon')], default='draft', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='tagcategory',
            unique_together={('name', 'base', 'relates_to', 'slug')},
        ),
    ]
