# Generated by Django 4.0.2 on 2022-04-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_resource_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcategory',
            name='maximum_tag_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nombre maximum de tags liés'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='est un brouillon'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='est un tag libre'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='main.tag', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='accepts_free_tags',
            field=models.BooleanField(default=True, verbose_name='accepte des tags libres'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='base',
            field=models.ForeignKey(blank=True, help_text="si une catégorie de tag n'est liée à aucune base, elle est globale", null=True, on_delete=django.db.models.deletion.CASCADE, to='main.base', verbose_name='lié à la base'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='is_draft',
            field=models.BooleanField(default=False, help_text="Une catégorie en brouillon est ignorée par l'appli", verbose_name='est un brouillon'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='is_multi_select',
            field=models.BooleanField(default=False, verbose_name='plusieurs choix possibles'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='name',
            field=models.CharField(max_length=20, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='relates_to',
            field=models.CharField(choices=[('Resource', 'Ressources'), ('User', 'Utilisateurs'), ('Base', 'Bases')], max_length=10, verbose_name='lié aux'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='required_to_be_public',
            field=models.BooleanField(default=False, verbose_name='remplissage obligatoire pour passer en public'),
        ),
    ]
