# Generated by Django 4.0.2 on 2022-04-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tagcategory_maximum_tag_number_alter_tag_is_draft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['index'], 'verbose_name': 'Bloc de contenu', 'verbose_name_plural': 'Blocs de contenu'},
        ),
        migrations.AddField(
            model_name='contentblock',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentblock',
            name='nb_col',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='main.resource'),
        ),
        migrations.AlterField(
            model_name='linkcontent',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='contentblock',
            unique_together={('resource', 'index')},
        ),
    ]
