# Generated by Django 4.0.2 on 2022-06-23 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_base_contact_base_contact_state_base_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='is_public',
        ),
        migrations.AlterField(
            model_name='base',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='base',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='root_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='resources', to='main.base',
                                    verbose_name='Base à laquelle la ressource est rattachée'),
        ),
    ]
