# Generated by Django 4.0.5 on 2022-06-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_base_is_public_remove_resource_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnfs_id_organization',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='resources', to='main.tag'),
        ),
    ]
