# Generated by Django 4.0.2 on 2022-05-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_contentblock_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentblock',
            old_name='parent_folder',
            new_name='section',
        ),
        migrations.AlterUniqueTogether(
            name='contentblock',
            unique_together={('resource', 'order', 'section')},
        ),
    ]
