# Generated by Django 4.0.5 on 2022-07-07 08:00

from django.db import migrations

from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_base_authorized_user_tags_base_authorized_users_and_more'),
    ]

    operations = [
        UnaccentExtension()
    ]
