# Generated by Django 4.0.2 on 2022-07-05 09:05

from django.db import migrations, models
import django.db.models.deletion


def to_resizable_image(apps, schema_editor):
    ResizableImage = apps.get_model("main", "ResizableImage")
    Base = apps.get_model("main", "Base")
    db_alias = schema_editor.connection.alias
    instances_to_update = []
    for base in Base.objects.using(db_alias).all().iterator():
        if base.profile_image_no_resize:
            resizable_profile_image = ResizableImage(image=base.profile_image_no_resize)
            resizable_profile_image.save()
            base.profile_image_id = resizable_profile_image.id
            instances_to_update.append(base)
    Base.objects.using(db_alias).bulk_update(instances_to_update, ["profile_image_id"])


def from_resizable_image(apps, schema_editor):
    Base = apps.get_model("main", "Base")
    db_alias = schema_editor.connection.alias
    instances_to_update = []
    for base in Base.objects.using(db_alias).all().iterator():
        resizable_profile_image = base.profile_image
        base.profile_image_no_resize = resizable_profile_image.image if resizable_profile_image else None
        instances_to_update.append(base)
    Base.objects.using(db_alias).bulk_update(instances_to_update, ["profile_image_no_resize"])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_base_authorized_user_tags_base_authorized_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResizableImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('scale_x', models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=5)),
                ('scale_y', models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=5)),
                ('relative_position_x', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('relative_position_y', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.RenameField(
            model_name='base',
            old_name='profile_image',
            new_name='profile_image_no_resize',
        ),
        migrations.AddField(
            model_name='base',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.resizableimage'),
        ),
        migrations.RunPython(to_resizable_image, from_resizable_image),
        migrations.RemoveField("base", "profile_image_no_resize"),
    ]
