# Generated by Django 4.0.2 on 2022-05-16 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_contentblock_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='creator_bases',
            field=models.ManyToManyField(related_name='created_ressources', to='main.Base', verbose_name='Bases qui ont créé la ressource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='root_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ressources', to='main.base'),
        ),
    ]
