# Generated by Django 4.0.2 on 2022-05-12 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_contentblock_section_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentblock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contentsection',
            name='is_foldable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentsection',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='main.contentsection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='contentblock',
            unique_together={('order', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='contentsection',
            unique_together={('resource', 'order')},
        ),
    ]
