# Generated by Django 4.0.5 on 2022-07-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_resizableimage_alter_base_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resizableimage',
            name='relative_position_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='resizableimage',
            name='relative_position_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='resizableimage',
            name='scale_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='resizableimage',
            name='scale_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='creator_bases',
            field=models.ManyToManyField(blank=True, related_name='created_resources', to='main.base', verbose_name='Bases qui ont créé la ressource'),
        ),
    ]
