# Generated by Django 4.0.2 on 2022-05-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_externalproducer_occupation_alter_tagcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcategory',
            name='slug',
            field=models.CharField(default='slug', max_length=40, verbose_name='Slug - à ne pas modifier'),
            preserve_default=False,
        ),
    ]
