# Generated by Django 4.0.5 on 2022-07-11 08:50

from django.db import migrations, models
from django.db.migrations import RunPython


def draft_to_private(apps, schema_editor):
    Base = apps.get_model("main", "Base")
    db_alias = schema_editor.connection.alias

    draft_bases = Base.objects.using(db_alias).filter(state="draft")
    draft_bases.update(state="private")


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_resizableimage_relative_position_x_and_more'),
    ]


    operations = [
        migrations.AlterField(
            model_name='base',
            name='state',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Privé'), ('draft', 'Brouillon')], default='private', max_length=10),
        ),
        migrations.RunPython(draft_to_private, RunPython.noop),
    ]
