# Generated by Django 4.0.2 on 2022-05-16 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_tagcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='producer_state',
            field=models.CharField(choices=[['me', 'celui qui ajouté la ressource'], ['know', 'producteur connu'], ['dont-know', 'producteur inconnu']], default='me', max_length=10),
        ),
        migrations.AlterField(
            model_name='externalproducer',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_producers', to='main.resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='root_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ressources', to='main.base', verbose_name='Base à laquelle la ressource est rattachée'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='description'),
        ),
    ]
