# Generated by Django 4.0.5 on 2022-07-15 11:44

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_base_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('category__relates_to__contains', 'Base'), ('category__relates_to__isnull', True), _connector='OR'), related_name='bases', to='main.tag'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('category__relates_to__contains', 'Resource'), ('category__relates_to__isnull', True), _connector='OR'), related_name='resources', to='main.tag'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='relates_to',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Resource', 'Ressources'), ('User', 'Utilisateurs'), ('Base', 'Bases'), ('Content', 'Contenus')], max_length=26, null=True, verbose_name='lié aux'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('category__relates_to__contains', 'User'), ('category__relates_to__isnull', True), _connector='OR'), related_name='users', to='main.tag'),
        ),
    ]
