# Generated by Django 4.0.5 on 2022-07-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_base_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_key',
        ),
        migrations.AlterField(
            model_name='base',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('category__relates_to', 'Bases'), ('category__relates_to__isnull', True), _connector='OR'), related_name='bases', to='main.tag'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('category__relates_to', 'Resource'), ('category__relates_to__isnull', True), _connector='OR'), related_name='resources', to='main.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cnfs_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id CNFS'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cnfs_id_organization',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="est employeur de l'id CNFS"),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='adresse email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='email validé'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='est admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='est super-utilisateur'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('category__relates_to', 'User'), ('category__relates_to__isnull', True), _connector='OR'), related_name='users', to='main.tag'),
        ),
    ]
