# Generated by Django 4.0.2 on 2022-05-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_resource_producer_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'ordering': ('slug',), 'verbose_name': 'Catégorie de tags', 'verbose_name_plural': 'Catégories de tags'},
        ),
        migrations.AddField(
            model_name='resource',
            name='is_linked_to_a_territory',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='slug',
            field=models.CharField(help_text='Convention : familleDeLaCatégorie + _ + ordreÀDeuxChiffresDansLaFamille + slugDeLaCatégorie, ex indexation_03format', max_length=40, verbose_name='Slug - à ne pas modifier'),
        ),
    ]
