# Generated by Django 4.0.2 on 2022-05-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_contentblock_unique_together_and_more'),
        ('main', '0014_resource_producer_state_and_more'),
    ]

    operations = [
    ]
