# Generated by Django 4.0.2 on 2022-05-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_tagcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='access_requires_user_account',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
