# Generated by Django 4.0.6 on 2022-09-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_licensetext_contentblock_license_knowledge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_created_on',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
