# Generated by Django 4.0.6 on 2022-09-16 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_resourcevisit_basevisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='collection',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.resizableimage'),
        ),
        migrations.AddField(
            model_name='resource',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.resizableimage'),
        ),
        migrations.AlterField(
            model_name='basevisit',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='main.base'),
        ),
        migrations.AlterField(
            model_name='basevisit',
            name='ip_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='resourcevisit',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='main.resource'),
        ),
        migrations.AlterField(
            model_name='resourcevisit',
            name='ip_hash',
            field=models.CharField(max_length=64),
        ),
    ]
