# Generated by Django 4.0.7 on 2022-09-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_resourcevisit_basevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
    ]
