# Generated by Django 4.0.2 on 2022-05-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_merge_20220517_0716'),
        ('main', '0017_alter_base_modified_alter_contentblock_modified_and_more'),
    ]

    operations = [
    ]
