# Generated by Django 4.0.7 on 2022-09-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_resourcevisit_basevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='basevisit',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='main.base'),
        ),
        migrations.AlterField(
            model_name='basevisit',
            name='ip_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='resourcevisit',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='main.resource'),
        ),
        migrations.AlterField(
            model_name='resourcevisit',
            name='ip_hash',
            field=models.CharField(max_length=64),
        ),
    ]
