# Generated by Django 4.0.6 on 2022-09-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_base_is_certified_alter_basevisit_instance_and_more'),
        ('main', '0018_collection_description_alter_basevisit_instance_and_more'),
        ('main', '0018_remove_resource_cover_image_collection_profile_image_and_more'),
    ]

    operations = [
    ]
