# Generated by Django 4.0.2 on 2022-05-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_merge_20220518_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentsection',
            options={'ordering': ['order'], 'verbose_name': 'Dossier de contenu', 'verbose_name_plural': 'Dossiers de contenu'},
        ),
        migrations.AddField(
            model_name='resource',
            name='state',
            field=models.CharField(choices=[('public', 'public'), ('private', 'Privé'), ('restricted', 'Restreint'), ('draft', 'Brouillon')], default='draft', max_length=10),
        ),
    ]
