# Generated by Django 4.0.7 on 2022-09-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_merge_20220917_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='is_certified',
            field=models.BooleanField(default=False, verbose_name='Est certifiée'),
        ),
    ]
