# Generated by Django 4.0.2 on 2022-05-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_contentsection_options_resource_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkcontent',
            name='display_mode',
        ),
        migrations.AddField(
            model_name='linkcontent',
            name='with_preview',
            field=models.BooleanField(default=False),
        ),
    ]
