# Generated by Django 4.0.6 on 2022-09-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_base_description_alter_base_is_certified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='base',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.resizableimage'),
        ),
        migrations.AlterField(
            model_name='base',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_base', to='main.resizableimage'),
        ),
    ]
