# Generated by Django 4.0.2 on 2022-05-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_resource_creator_bases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagcategory',
            name='is_multi_select',
        ),
    ]
