# Generated by Django 4.0.7 on 2022-10-05 18:11

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_base_cover_image_alter_base_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content', django_quill.fields.QuillField()),
                ('description', models.CharField(max_length=180, verbose_name='description (SEO)')),
                ('icon', models.CharField(blank=True, default='', help_text="nom de l'icone remix icon, type ri-search-line", max_length=50, verbose_name='icone')),
                ('order', models.IntegerField(verbose_name='ordre dans le menu')),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='faire apparaitre la page dans le menu')),
                ('slug', models.CharField(help_text="nom de la page dans l'URL", max_length=100, primary_key=True, serialize=False, verbose_name='slug')),
                ('title', models.CharField(max_length=50, verbose_name='titre')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
