# Generated by Django 4.0.2 on 2022-05-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_tagcategory_is_multi_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
