# Generated by Django 4.0.2 on 2022-06-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_base_is_public_resource_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.CharField(blank=True, max_length=560, null=True),
        ),
    ]
