# Generated by Django 4.0.7 on 2022-10-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalproducer',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
