# Generated by Django 4.0.6 on 2022-10-05 08:03
from django.db import migrations, models
import functools
import main.models.utils
import versatileimagefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0024_alter_externalproducer_email_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='resizableimage',
            name='cropped_image',
            field=versatileimagefield.fields.VersatileImageField(default=1, editable=False, upload_to=functools.partial(
                main.models.utils.upload_image_location, *(), **{'cropped': True})),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resizableimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to=main.models.utils.upload_image_location),
        ),
        migrations.AddField(
            model_name='resizableimage',
            name='relative_height',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='resizableimage',
            name='relative_left',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resizableimage',
            name='relative_top',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resizableimage',
            name='relative_width',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
