# Generated by Django 4.0.2 on 2022-06-03 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_alter_resource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontent',
            name='with_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='base',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to=settings.AUTH_USER_MODEL,
                                         verbose_name='administrateurs'),
        ),
        migrations.AlterField(
            model_name='base',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='La base est publique'),
        ),
        migrations.AlterField(
            model_name='base',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner',
                                    to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
        migrations.AlterField(
            model_name='base',
            name='title',
            field=models.CharField(max_length=100, verbose_name='titre'),
        ),
    ]
