# Generated by Django 4.0.2 on 2022-06-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_filecontent_with_preview_alter_base_admins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='order',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='order',
            field=models.BigIntegerField(),
        ),
    ]
