# Generated by Django 4.0.2 on 2022-06-06 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_contentblock_order_alter_contentsection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_created_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
