# Generated by Django 4.0.2 on 2022-06-04 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_contentblock_order_alter_contentsection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
