# Generated by Django 4.0.6 on 2022-10-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20221011_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resizableimage',
            name='relative_position_x',
        ),
        migrations.RemoveField(
            model_name='resizableimage',
            name='relative_position_y',
        ),
        migrations.RemoveField(
            model_name='resizableimage',
            name='scale_x',
        ),
        migrations.RemoveField(
            model_name='resizableimage',
            name='scale_y',
        ),
        # older stuff
        migrations.RemoveField(
            model_name='resource',
            name='thumbnail',
        ),
        # other stuff
        migrations.AlterField(
            model_name='base',
            name='cover_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='base_cover', to='main.resizableimage'),
        ),
        migrations.AlterField(
            model_name='base',
            name='profile_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='base_profile', to='main.resizableimage'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='profile_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='collection_profile', to='main.resizableimage'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='profile_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='resource_profile', to='main.resizableimage'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='license_text',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to='main.licensetext', verbose_name='Détail de licence propriétaire'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='license_text',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to='main.licensetext', verbose_name='Détail de licence propriétaire'),
        ),
    ]
