# Generated by Django 4.0.2 on 2022-06-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_resource_resource_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
