# Generated by Django 4.0.2 on 2022-06-06 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0027_resource_cover_image_resource_resource_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('can_write', models.BooleanField(default=False, verbose_name='accès en écriture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='nom du groupe')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='label_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='label_state',
            field=models.CharField(blank=True, choices=[('', 'Non demandé'), ('pending', 'En cours'), ('refused', 'Refusé'), ('accepted', 'Accepté')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='root_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='main.base', verbose_name='Base à laquelle la ressource est rattachée'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ressources', to='main.Tag'),
        ),
        migrations.DeleteModel(
            name='ContributorProfile',
        ),
        migrations.AddField(
            model_name='resourceusergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_user_groups', to='main.usergroup'),
        ),
        migrations.AddField(
            model_name='resourceusergroup',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_user_groups', to='main.resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='groups',
            field=models.ManyToManyField(blank=True, through='main.ResourceUserGroup', to='main.UserGroup'),
        ),
    ]
