# Generated by Django 4.0.7 on 2022-10-26 07:39

from django.db import migrations, models
from tqdm import tqdm


def re_save_links(apps, _):
    LinkContent = apps.get_model("main", "LinkContent")
    n_deleted = 0
    n_resaved = 0
    for link in tqdm(LinkContent.objects.all()):
        if not link.link:
            link.delete()
            n_deleted += 1
            continue
        link.save()
        n_resaved += 1
    print(f"done re-saving links, deleted {n_deleted} empty links, re-saved {n_resaved}")


def do_nothing(_, _2):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20221011_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkcontent',
            name='target_description',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='linkcontent',
            name='target_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkcontent',
            name='target_title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.RunPython(re_save_links, do_nothing)
    ]
