# Generated by Django 4.0.2 on 2022-06-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0028_resourceusergroup_usergroup_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_grid_view_enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_grid_view_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
