# Generated by Django 4.0.7 on 2022-10-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_linkcontent_target_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='producer_state',
            field=models.CharField(blank=True, choices=[['me', 'celui qui ajouté la ressource'], ['know', 'producteur connu'], ['dont-know', 'producteur inconnu']], max_length=10, null=True),
        ),
    ]
