# Generated by Django 4.0.2 on 2022-06-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_resource_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
