# Generated by Django 4.0.2 on 2022-06-05 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_resource_resource_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_created_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
