# Generated by Django 4.0.2 on 2022-06-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0029_resource_is_grid_view_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='title',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
