# Generated by Django 4.0.2 on 2022-06-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_contentblock_title_alter_contentsection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
