# Generated by Django 4.0.7 on 2022-11-01 17:28

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_externalproducer_website_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField(verbose_name='contenu')),
                ('title', models.CharField(max_length=100, verbose_name='titre')),
                ('order', models.IntegerField(verbose_name='ordre dans le menu')),
                ('slug', models.CharField(max_length=50, verbose_name='identifiant')),
                ('page', models.CharField(max_length=30, verbose_name="s'applique à la page")),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
