# Generated by Django 4.0.2 on 2022-06-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_contentblock_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25, verbose_name='nom')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='main.base')),
                ('resources', models.ManyToManyField(blank=True, related_name='collections', to='main.Resource')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('name', 'base')},
            },
        ),
    ]
