# Generated by Django 4.0.7 on 2022-11-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_intro_options_alter_intro_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='position',
            field=models.CharField(choices=[['top', 'au-dessus'], ['bottom', 'en-dessous'], ['right', 'à droite'], ['left', 'à gauche']], default='bottom', max_length=6),
        ),
        migrations.AlterField(
            model_name='intro',
            name='image',
            field=models.ImageField(blank=True,
                                    help_text='Mettre une image légère, de largeur min 310px, max 620px',
                                    null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='intro',
            name='page',
            field=models.CharField(
                help_text="Demander aux développeurs quoi remplir ici ; les éléments commençant par<pre style='display:inline;padding:2px 4px;background:#e9e9e9'>draft</pre>sont ignorés.",
                max_length=30, verbose_name="s'applique à la page"),
        ),
        migrations.AlterField(
            model_name='intro',
            name='slug',
            field=models.CharField(
                help_text="<b>Confirmer avec les devs avant changement ou ajout !</b> Si plusieurs bulles s'appliquent au même contenu, mettre deux fois le même identifiant.",
                max_length=50, verbose_name='identifiant'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='page',
            field=models.CharField(
                help_text="Demander aux développeurs quoi remplir ici ; ; les éléments commençant par<pre style='display:inline;padding:2px 4px;background:#e9e9e9'>draft</pre>sont ignorés.",
                max_length=30, verbose_name="s'applique à la page"),
        ),
        migrations.AlterField(
            model_name='intro',
            name='slug',
            field=models.CharField(
                help_text="<b>Confirmer avec les devs avant changement ou ajout !</b> Si plusieurs bulles s'appliquent au même contenu, mettre deux fois le même identifiant. ; les éléments commençant par<pre style='display:inline;padding:2px 4px;background:#e9e9e9'>draft</pre>sont ignorés.",
                max_length=50, verbose_name='identifiant'),
        ),
    ]
