# Generated by Django 4.0.7 on 2022-11-09 20:42

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_intro_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField(verbose_name='contenu')),
                ('slug', models.CharField(help_text="<b>Ne pas faire de bêtise avec ce champ !</b> En général, ce champ n'a pas besoin d'être modifié.", max_length=50, verbose_name='identifiant')),
            ],
            options={
                'verbose_name': 'bloc de texte',
                'verbose_name_plural': 'blocs de texte',
            },
        ),
    ]
