# Generated by Django 4.0.7 on 2022-11-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_textblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='national_cartography_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='base',
            name='social_media_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='base',
            name='social_media_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='base',
            name='social_media_mastodon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='base',
            name='social_media_twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='base',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
