# Generated by Django 4.0.7 on 2022-11-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_seenpageintros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'ordering': ('order',), 'verbose_name': 'Catégorie de tags', 'verbose_name_plural': 'Catégories de tags'},
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='order',
            field=models.FloatField(default=0),
        ),
    ]
