# Generated by Django 4.0.8 on 2022-11-22 10:17

from django.db import migrations
import main.models.utils


def migrateDescription(apps, _):
    Base = apps.get_model("main", "Base")
    for base in Base.objects.all():
        base.description = base.description
        base.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_tagcategory_options_tagcategory_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='description',
            field=main.models.utils.RichText(blank=True, null=True),
        ),
        migrations.RunPython(migrateDescription, migrations.RunPython.noop),
    ]

