# Generated by Django 4.0.8 on 2022-11-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_base_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='confirmed_duplicates',
            field=models.ManyToManyField(blank=True, related_name='confirmed_duplicates_by_ressources', to='main.resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='ignored_duplicates',
            field=models.ManyToManyField(blank=True, related_name='ignored_duplicates_by_ressources', to='main.resource'),
        ),
    ]
