# Generated by Django 4.0.8 on 2022-12-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_base_own_resource_count_base_pinned_resources_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='confirmed_duplicates',
            field=models.ManyToManyField(blank=True, to='main.resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='ignored_duplicates',
            field=models.ManyToManyField(blank=True, to='main.resource'),
        ),
    ]
