# Generated by Django 4.0.8 on 2022-12-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_resource_confirmed_duplicates_and_more'),
        ('main', '0040_base_own_resource_count_base_pinned_resources_count_and_more'),
    ]

    operations = [
    ]
