# Generated by Django 4.0.8 on 2022-12-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_resource_confirmed_duplicates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='confirmed_duplicates',
            field=models.ManyToManyField(blank=True, to='main.resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ignored_duplicates',
            field=models.ManyToManyField(blank=True, to='main.resource'),
        ),
    ]
