# Generated by Django 4.0.8 on 2022-12-06 14:47

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_resource_confirmed_duplicates_and_more'),
    ]

    operations = [
        TrigramExtension()
    ]
