# Generated by Django 4.0.8 on 2022-12-12 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_seenintroslug_remove_intro_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='show_latest_additions',
            field=models.BooleanField(default=True, verbose_name='Afficher les derniers ajouts'),
        ),
        migrations.CreateModel(
            name='BaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='titre')),
                ('description', models.CharField(max_length=240, verbose_name='description')),
                ('type', models.CharField(choices=[('resources', 'Ressources'), ('collections', 'Collections')], max_length=32, verbose_name='type')),
                ('position', models.PositiveSmallIntegerField(verbose_name='position')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.base')),
                ('collections', models.ManyToManyField(blank=True, related_name='collection_sections', to='main.collection', verbose_name='Collection')),
                ('resources', models.ManyToManyField(blank=True, related_name='resource_sections', to='main.resource', verbose_name='Resource')),
            ],
            options={
                'verbose_name': 'Rubrique',
                'ordering': ['position'],
            },
        ),
    ]
