# Generated by Django 4.0.8 on 2022-12-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_base_show_latest_additions_basesection'),
        ('main', '0044_usersearch'),
    ]

    operations = [
    ]
