# Generated by Django 4.0.7 on 2022-12-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_basebookmark'),
        ('main', '0045_merge_20221214_1008'),
    ]

    operations = [
    ]
