# Generated by Django 4.0.8 on 2022-12-16 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_merge_0044_basebookmark_0045_merge_20221214_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebookmark',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='main.base'),
        ),
        migrations.AlterField(
            model_name='basebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
