# Generated by Django 4.0.7 on 2023-01-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_basebookmark_base_alter_basebookmark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='bookmarked_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
