# Generated by Django 4.0.7 on 2023-01-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_basebookmark_base_alter_basebookmark_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesection',
            name='description',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='description'),
        ),
    ]
