# Generated by Django 4.0.7 on 2023-01-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_basesection_description'),
        ('main', '0048_base_bookmarked_count'),
    ]

    operations = [
    ]
