# Generated by Django 4.0.7 on 2023-01-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_merge_20230104_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontent',
            name='image_alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
