# Generated by Django 4.0.7 on 2023-01-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_criterion_alter_page_content_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='can_evaluate',
            field=models.BooleanField(default=True, verbose_name='Évaluation activées'),
        ),
    ]
