# Generated by Django 4.0.9 on 2023-02-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_resource_can_evaluate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='users',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='url',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='has_global_license',
            field=models.BooleanField(default=True, verbose_name='Les contenus ont globalement la même licence'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='label_state',
            field=models.CharField(blank=True, choices=[('', 'Non demandé'), ('pending', 'En cours'), ('refused', 'Refusé'), ('accepted', 'Accepté')], default='', max_length=10, verbose_name='État de la labélisation'),
        ),
        migrations.DeleteModel(
            name='ResourceUserGroup',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
